apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-app
  namespace: argocd
  spec:
    project: default

    source:
      repoURL: https://github.com/nicolasgomes1/kubernetes.git
      targetRevision: HEAD
      path: pg

    destination:
      server: 'https://kubernetes.default.svc'
      namespace: myapp

    SyncPolicy:
      SyncOptions:
      - CreateNamespace=true
      - Automated:
          prune: true
          selfHeal: true